const $ = s => document.querySelector(s);
const state = { page:'home', user: JSON.parse(localStorage.getItem('ss_user')||'null'), cart: JSON.parse(localStorage.getItem('ss_cart')||'[]'), products: JSON.parse(localStorage.getItem('ss_products')||'null') };
state.products ||= [
 {id:1,name:'Linen Day Shirt',category:'Apparel',price:1299,icon:'👔'}, {id:2,name:'Sage Carry Tote',category:'Accessories',price:899,icon:'👜'}, {id:3,name:'Ceramic Coffee Set',category:'Home',price:1499,icon:'☕'}, {id:4,name:'Studio Headphones',category:'Tech',price:2499,icon:'🎧'}, {id:5,name:'Daily Journal',category:'Stationery',price:399,icon:'📓'}, {id:6,name:'Canvas Sneakers',category:'Footwear',price:1899,icon:'👟'}
];
const save=()=>{localStorage.setItem('ss_cart',JSON.stringify(state.cart));localStorage.setItem('ss_products',JSON.stringify(state.products));localStorage.setItem('ss_user',JSON.stringify(state.user))};
const money=n=>'₹'+Number(n).toLocaleString('en-IN'); const go=p=>{state.page=p;render()};
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function header(){const count=state.cart.reduce((n,x)=>n+x.qty,0);$('#siteHeader').innerHTML=`<div class="topbar">FREE DELIVERY ON ORDERS ABOVE ₹999</div><nav class="nav"><a class="brand" href="#" onclick="go('home')">Shop<i>Swift</i></a><div class="links"><a class="hide-mobile" href="#" onclick="go('home')">Shop</a>${state.user?`<a href="#" onclick="go('${state.user.role==='admin'?'admin':'dashboard'}')">${state.user.name}</a><a href="#" onclick="logout()">Logout</a>`:`<a href="#" onclick="go('login')">Sign in</a>`}<a href="#" onclick="go('cart')">Cart <b class="cart-count">${count}</b></a></div></nav>`}
function productCard(p){return `<article class="product"><div class="product-image" style="cursor:pointer" onclick="go('product-${p.id}')">${p.icon}</div><div class="product-info"><small>${p.category}</small><h3 style="cursor:pointer" onclick="go('product-${p.id}')">${p.name}</h3><div class="product-row"><span class="price">${money(p.price)}</span><button class="circle" onclick="addCart(${p.id})" aria-label="Add ${p.name}">+</button></div></div></article>`}
function productPage(id){let p=state.products.find(x=>x.id===id);if(!p)return home();return `<div class="two-col" style="margin:48px auto;max-width:880px;align-items:center"><div class="product-image" style="height:360px;border-radius:14px;font-size:10rem">${p.icon}</div><div><div class="eyebrow">${p.category}</div><h1 class="page-title" style="margin:10px 0">${p.name}</h1><p class="price" style="font-size:1.35rem">${money(p.price)}</p><p style="color:var(--muted);line-height:1.7">A carefully selected everyday essential, designed to be useful, beautiful, and easy to enjoy.</p><button class="btn" onclick="addCart(${p.id})">Add to cart</button><p class="hint">Free delivery on orders above ₹999 · Cash on delivery available</p></div></div>`}
function home(){return `<section class="hero"><div class="hero-copy"><div class="eyebrow">Curated for everyday</div><h1>Objects to enjoy, every day.</h1><p>Thoughtful finds for your wardrobe, desk, and home. Made for the small moments that make a day feel good.</p><button class="btn" onclick="document.getElementById('products').scrollIntoView({behavior:'smooth'})">Shop collection</button></div><div class="hero-art">🛍️</div></section><section id="products"><div class="section-head"><div><span>Our favourites</span><h2>Fresh arrivals</h2></div><span>${state.products.length} products</span></div><div class="grid">${state.products.map(productCard).join('')}</div></section>`}
function auth(mode){let register=mode==='register';return `<section class="auth"><h1>${register?'Create account':'Welcome back'}</h1><p>${register?'Join ShopSwift and start collecting your favourites.':'Sign in to view orders and checkout faster.'}</p><form onsubmit="${register?'register(event)':'login(event)'}">${register?`<div class="field"><label>Full name</label><input name="name" required placeholder="Your name"></div>`:''}<div class="field"><label>Email address</label><input type="email" name="email" required placeholder="you@example.com"></div><div class="field"><label>Password</label><input type="password" name="password" required placeholder="••••••••"></div><button class="btn full">${register?'Create account':'Sign in'}</button></form><p class="hint">${register?'Already have an account?':'New to ShopSwift?'} <a href="#" onclick="go('${register?'login':'register'}')">${register?'Sign in':'Create an account'}</a></p><p class="hint">Admin demo: <a href="#" onclick="adminLogin()">sign in as admin</a></p></section>`}
function dashboard(){return appLayout(`<div class="welcome"><div class="eyebrow" style="color:#afcbb7">My account</div><h1>Hello, ${state.user.name.split(' ')[0]}.</h1><p>Everything you love, all in one place.</p></div><div class="section-head"><h2>Recent orders</h2></div>${orders().filter(o=>o.email===state.user.email).length?orders().filter(o=>o.email===state.user.email).map(orderRow).join(''):`<div class="panel empty">No orders just yet. <a href="#" onclick="go('home')">Start shopping →</a></div>`}`, 'dashboard')}
function appLayout(content,active){return `<div class="layout"><aside class="side"><a class="${active==='dashboard'?'active':''}" href="#" onclick="go('dashboard')">My dashboard</a><a class="${active==='orders'?'active':''}" href="#" onclick="go('orders')">My orders</a><a href="#" onclick="go('home')">Continue shopping</a></aside><div>${content}</div></div>`}
function cart(){if(!state.cart.length)return `<div class="empty"><h1 class="page-title">Your cart is empty</h1><p>Find something lovely to take home.</p><button class="btn" onclick="go('home')">Shop products</button></div>`;let total=state.cart.reduce((s,x)=>s+x.price*x.qty,0);return `<h1 class="page-title" style="margin-top:32px">Shopping cart</h1><div class="cart-layout"><div class="panel">${state.cart.map(x=>`<div class="cart-item"><div class="product-image">${x.icon}</div><div><h3>${x.name}</h3><p>${money(x.price)}</p><button class="btn secondary" style="padding:5px 9px;font-size:.75rem" onclick="removeCart(${x.id})">Remove</button></div><div class="quantity"><button onclick="changeQty(${x.id},-1)">−</button><span>${x.qty}</span><button onclick="changeQty(${x.id},1)">+</button></div></div>`).join('')}</div><aside class="summary"><h2>Order summary</h2><div class="summary-row"><span>Subtotal</span><b>${money(total)}</b></div><div class="summary-row"><span>Delivery</span><b>${total>=999?'Free':'₹99'}</b></div><div class="summary-row total"><span>Total</span><span>${money(total+(total>=999?0:99))}</span></div><button class="btn full" onclick="go('${state.user?'checkout':'login'}')">Checkout</button></aside></div>`}
function checkout(){if(!state.cart.length)return cart();return `<div class="auth" style="max-width:650px"><h1>Checkout</h1><p>Almost there. We currently accept cash on delivery.</p><form onsubmit="placeOrder(event)"><div class="two-col"><div class="field"><label>Full name</label><input name="name" value="${state.user.name}" required></div><div class="field"><label>Phone number</label><input name="phone" required placeholder="10-digit mobile number"></div></div><div class="field"><label>Delivery address</label><textarea name="address" required placeholder="House no., street, city, PIN code"></textarea></div><div class="notice">Payment method: <strong>Cash on Delivery</strong></div><br><button class="btn full">Place order</button></form></div>`}
function orders(){return JSON.parse(localStorage.getItem('ss_orders')||'[]')};function orderRow(o){return `<div class="panel" style="margin-bottom:12px;display:flex;justify-content:space-between;align-items:center"><div><b>${o.id}</b><p style="margin:5px 0;color:var(--muted);font-size:.88rem">${o.date} · ${o.items.length} item(s)</p></div><div style="text-align:right"><b>${money(o.total)}</b><br><span class="status">${o.status}</span></div></div>`}
function ordersPage(){return appLayout(`<h1 class="page-title">My orders</h1><div style="margin-top:18px">${orders().filter(o=>o.email===state.user.email).map(orderRow).join('')||'<div class="panel empty">No orders placed yet.</div>'}</div>`,'orders')}
function admin(){let os=orders(), users=JSON.parse(localStorage.getItem('ss_customers')||'[]');return `<div class="layout"><aside class="side"><a class="active" href="#" onclick="go('admin')">Overview</a><a href="#" onclick="go('adminProducts')">Products</a><a href="#" onclick="go('adminOrders')">Orders</a><a href="#" onclick="go('adminCustomers')">Customers</a></aside><div><div class="welcome"><div class="eyebrow" style="color:#afcbb7">Admin dashboard</div><h1>Store overview</h1><p>Manage your catalog, customers, and customer orders.</p></div><div class="stats"><div class="stat"><b>${state.products.length}</b><span>Products</span></div><div class="stat"><b>${users.length}</b><span>Customers</span></div><div class="stat"><b>${os.length}</b><span>Orders received</span></div></div><div class="panel"><h2 style="margin-top:0">Recent orders</h2>${os.slice(-4).reverse().map(orderRow).join('')||'<p class="hint">No orders yet.</p>'}</div></div></div>`}
function adminProducts(){return adminLayout('Products',`<button class="btn" onclick="go('addProduct')">+ Add product</button><div class="grid" style="margin-top:20px">${state.products.map(p=>`<article class="product"><div class="product-image">${p.icon}</div><div class="product-info"><small>${p.category}</small><h3>${p.name}</h3><div class="product-row"><b>${money(p.price)}</b><button class="btn danger" style="padding:7px 9px;font-size:.75rem" onclick="deleteProduct(${p.id})">Delete</button></div></div></article>`).join('')}</div>`)}
function adminLayout(title,content){return `<div class="layout"><aside class="side"><a href="#" onclick="go('admin')">Overview</a><a class="${title==='Products'?'active':''}" href="#" onclick="go('adminProducts')">Products</a><a class="${title==='Orders'?'active':''}" href="#" onclick="go('adminOrders')">Orders</a><a class="${title==='Customers'?'active':''}" href="#" onclick="go('adminCustomers')">Customers</a></aside><div><h1 class="page-title">${title}</h1><div class="panel" style="margin-top:18px">${content}</div></div></div>`}
function addProduct(){return adminLayout('Add product',`<form onsubmit="createProduct(event)"><div class="two-col"><div class="field"><label>Product name</label><input name="name" required></div><div class="field"><label>Category</label><input name="category" required></div></div><div class="two-col"><div class="field"><label>Price (₹)</label><input type="number" name="price" min="1" required></div><div class="field"><label>Product emoji</label><input name="icon" value="🛍️" maxlength="4"></div></div><button class="btn">Save product</button></form>`)}
function adminOrders(){let os=orders();return adminLayout('Orders',`<div class="table-wrap"><table class="table"><thead><tr><th>Order</th><th>Customer</th><th>Address</th><th>Total</th><th>Status</th></tr></thead><tbody>${os.map(o=>`<tr><td>${o.id}<br><small>${o.date}</small></td><td>${o.customer}<br><small>${o.phone}</small></td><td>${o.address}</td><td>${money(o.total)}</td><td><span class="status">${o.status}</span></td></tr>`).join('')||'<tr><td colspan="5">No orders yet.</td></tr>'}</tbody></table></div>`)}
function adminCustomers(){let users=JSON.parse(localStorage.getItem('ss_customers')||'[]');return adminLayout('Customers',`<div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Email</th><th>Joined</th></tr></thead><tbody>${users.map(u=>`<tr><td>${u.name}</td><td>${u.email}</td><td>${u.joined}</td></tr>`).join('')||'<tr><td colspan="3">No customers registered yet.</td></tr>'}</tbody></table></div>`)}
function addCart(id){let p=state.products.find(x=>x.id===id), x=state.cart.find(x=>x.id===id);x?x.qty++:state.cart.push({...p,qty:1});save();header();toast(`${p.name} added to cart`)}function removeCart(id){state.cart=state.cart.filter(x=>x.id!==id);save();render()}function changeQty(id,n){let x=state.cart.find(x=>x.id===id);x.qty+=n;if(x.qty<1)removeCart(id);else{save();render()}}
function register(e){e.preventDefault();let f=new FormData(e.target),u={name:f.get('name'),email:f.get('email'),role:'user'};let users=JSON.parse(localStorage.getItem('ss_customers')||'[]');if(users.some(x=>x.email===u.email)){toast('An account with this email already exists');return}u.joined=new Date().toLocaleDateString();users.push(u);localStorage.setItem('ss_customers',JSON.stringify(users));state.user=u;save();toast('Account created successfully');go('dashboard')}function login(e){e.preventDefault();let email=new FormData(e.target).get('email'),u=JSON.parse(localStorage.getItem('ss_customers')||'[]').find(x=>x.email===email);if(!u){toast('Account not found. Please register first.');return}state.user=u;save();go('dashboard')}function adminLogin(){state.user={name:'Admin',email:'admin@shopswift.com',role:'admin'};save();go('admin')}function logout(){state.user=null;save();go('home')}
function placeOrder(e){e.preventDefault();let f=new FormData(e.target),total=state.cart.reduce((s,x)=>s+x.price*x.qty,0)+(state.cart.reduce((s,x)=>s+x.price*x.qty,0)>=999?0:99), os=orders();os.push({id:'ORD-'+String(Date.now()).slice(-6),date:new Date().toLocaleDateString(),email:state.user.email,customer:f.get('name'),phone:f.get('phone'),address:f.get('address'),items:state.cart,total,status:'Order placed'});localStorage.setItem('ss_orders',JSON.stringify(os));state.cart=[];save();toast('Order placed! We will notify you shortly.');go('orders')}
function createProduct(e){e.preventDefault();let f=new FormData(e.target);state.products.push({id:Date.now(),name:f.get('name'),category:f.get('category'),price:Number(f.get('price')),icon:f.get('icon')||'🛍️'});save();toast('Product added');go('adminProducts')}function deleteProduct(id){state.products=state.products.filter(p=>p.id!==id);save();render();toast('Product removed')}
function render(){header();let views={home,login:()=>auth('login'),register:()=>auth('register'),dashboard,cart,checkout,orders:ordersPage,admin,adminProducts,addProduct,adminOrders,adminCustomers};if(['dashboard','orders','checkout'].includes(state.page)&&!state.user)state.page='login';if(state.page.startsWith('admin')&&state.user?.role!=='admin')state.page='login';$('#app').innerHTML=state.page.startsWith('product-')?productPage(Number(state.page.split('-')[1])):(views[state.page]||home)()};render();
